// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: test_time.sql

package queries

import (
	"context"
	"database/sql"
)

const getTestTimeByID = `-- name: GetTestTimeByID :one
SELECT id, val FROM test_time WHERE id = ? LIMIT 1
`

func (q *Queries) GetTestTimeByID(ctx context.Context, id int64) (TestTime, error) {
	row := q.db.QueryRowContext(ctx, getTestTimeByID, id)
	var i TestTime
	err := row.Scan(&i.ID, &i.Val)
	return i, err
}

const insertTestTime = `-- name: InsertTestTime :one
INSERT INTO test_time (val) VALUES (?)
RETURNING id
`

func (q *Queries) InsertTestTime(ctx context.Context, val sql.NullTime) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertTestTime, val)
	var id int64
	err := row.Scan(&id)
	return id, err
}
